Fixes #31
nautobot/nautobot-plugin-chatops-meraki pull request #32
Opened 2022-08-30 06:36 UTC by ubajze

Fixes #31

2022-09-26 13:22 UTC, jeffkala commented
@ubajze pylint is failing.

2022-09-26 19:35 UTC, ubajze commented
@jeffkala I think it should be good now

2022-10-03 13:17 UTC, jeffkala requested changes

2022-10-03 13:17 UTC, jeffkala commented on nautobot_plugin_chatops_meraki/worker.py
> +except KeyError as e:
```suggestion
except KeyError as err:
```

2022-10-03 13:17 UTC, jeffkala commented on nautobot_plugin_chatops_meraki/worker.py
> +        raise Exception("Unable to find the Meraki API key.") from e
```suggestion
        raise Exception("Unable to find the Meraki API key.") from err
```

2022-10-11 13:40 UTC, jeffkala approved these changes

2022-10-11 13:40 UTC, merged